language: objective-c
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-ri --no-rdoc
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - cd Bootstrap; pod update ; cd ..
xcode_workspace: Bootstrap/ARAnalyticsTests.xcworkspace
xcode_scheme: ARAnalyticsBootstrapiOS
xcode_sdk: iphonesimulator
